---

#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

anchorLinks:
  - link: &grafana-home
      url: "https://grafana.com/"
      params: "time"

#------------------------------------------------------------------------------
# Panel Config

cellIdPreamble: "cell-"
cells: 
  drawio:
    link:
      url: "https://erikaalvarez.grafana.net/d/video-streaming-dashboard/video-streaming-dashboard?orgId=1&viewPanel=2&from=now-6h&to=now&timezone=browser&var-server="
      params: "none"          # we already set from/to in the URL; don't append more
      sameTab: true           # v1.14.0+ opens in same tab unless Ctrl/Shift is held
  docs:
    link:
      action: "popup"
      title: "Video streaming — Panel 2"
      url: "/d-solo/video-streaming-dashboard/video-streaming-dashboard?orgId=1&panelId=2&from=now-6h&to=now&timezone=browser&var-server="
      width: 1100
      height: 700
  inbox_depth:
    dataRef: "test-data-large-sin"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds:
        - {color: "green", level: 0}
        - {color: "orange", level: 500}
        - {color: "red", level: 1000}
    link: *grafana-home
  db_transactions:
    dataRef: "test-data-large-cos"
    label:
      separator: "cr"
      units: "ops"
      decimalPoints: 0
    fillColor:
      gradientMode: "hue"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "orange", level: 400}
        - {color: "red", level: 800}
    link: *grafana-home
  start_rate:
    dataRef: "test-data-small-sin"
    label:
      separator: "colon"
      units: "pps"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds:
        - {color: "green", level: 0}
        - {color: "orange", level: 100}
    link: *grafana-home
  active_workers:
    dataRef: "test-data-small-cos"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds:
        - {color: "#888888", level: 0}
        - {color: "light-blue", level: 100}
