---
#------------------------------------------------------------------------------
# Panel Config

cellIdPreamble: "cell-"
cells:
  # ==============================
  # === CHANNELS (A/B/C) ========
  # ==============================
  channel_a_sdi_health:
    dataRef: "channel_a_sdi_health"
    fillColor:
      gradientMode: "none"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "yellow", level: 1 }
        - { color: "green", level: 2 }
    label:
      units: "status_text"
      mappings:
        - { value: 0, text: "FAIL" }
        - { value: 1, text: "WARN" }
        - { value: 2, text: "OK" }

  channel_a_srt_health:
    dataRef: "channel_a_srt_health"
    fillColor:
      gradientMode: "none"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "yellow", level: 1 }
        - { color: "green", level: 2 }
    label:
      units: "status_text"
      mappings:
        - { value: 0, text: "FAIL" }
        - { value: 1, text: "WARN" }
        - { value: 2, text: "OK" }

  channel_a_general_health:
    dataRef: "channel_a_general_health"
    fillColor:
      gradientMode: "none"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "yellow", level: 1 }
        - { color: "green", level: 2 }
    label:
      units: "status_text"
      mappings:
        - { value: 0, text: "FAIL" }
        - { value: 1, text: "WARN" }
        - { value: 2, text: "OK" }

  channel_b_sdi_health:
    dataRef: "channel_b_sdi_health"
    fillColor:
      gradientMode: "none"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "yellow", level: 1 }
        - { color: "green", level: 2 }
    label:
      units: "status_text"
      mappings:
        - { value: 0, text: "FAIL" }
        - { value: 1, text: "WARN" }
        - { value: 2, text: "OK" }

  channel_b_srt_health:
    dataRef: "channel_b_srt_health"
    fillColor:
      gradientMode: "none"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "yellow", level: 1 }
        - { color: "green", level: 2 }
    label:
      units: "status_text"
      mappings:
        - { value: 0, text: "FAIL" }
        - { value: 1, text: "WARN" }
        - { value: 2, text: "OK" }

  channel_b_general_health:
    dataRef: "channel_b_general_health"
    fillColor:
      gradientMode: "none"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "yellow", level: 1 }
        - { color: "green", level: 2 }
    label:
      units: "status_text"
      mappings:
        - { value: 0, text: "FAIL" }
        - { value: 1, text: "WARN" }
        - { value: 2, text: "OK" }

  channel_c_sdi_health:
    dataRef: "channel_c_sdi_health"
    fillColor:
      gradientMode: "none"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "yellow", level: 1 }
        - { color: "green", level: 2 }
    label:
      units: "status_text"
      mappings:
        - { value: 0, text: "FAIL" }
        - { value: 1, text: "WARN" }
        - { value: 2, text: "OK" }

  channel_c_srt_health:
    dataRef: "channel_c_srt_health"
    fillColor:
      gradientMode: "none"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "yellow", level: 1 }
        - { color: "green", level: 2 }
    label:
      units: "status_text"
      mappings:
        - { value: 0, text: "FAIL" }
        - { value: 1, text: "WARN" }
        - { value: 2, text: "OK" }

  channel_c_general_health:
    dataRef: "channel_c_general_health"
    fillColor:
      gradientMode: "none"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "yellow", level: 1 }
        - { color: "green", level: 2 }
    label:
      units: "status_text"
      mappings:
        - { value: 0, text: "FAIL" }
        - { value: 1, text: "WARN" }
        - { value: 2, text: "OK" }

  # ==============================
  # === ENCODERS & TRANSCODER ====
  # ==============================
  encoder_1_status_box:
    dataRef: "encoder_1_status_box"
    fillColor:
      gradientMode: "none"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
    label:
      units: "status_text"
      mappings:
        - { value: 0, text: "ERROR" }
        - { value: 1, text: "LIVE" }

  encoder_2_status_box:
    dataRef: "encoder_2_status_box"
    fillColor:
      gradientMode: "none"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
    label:
      units: "status_text"
      mappings:
        - { value: 0, text: "ERROR" }
        - { value: 1, text: "LIVE" }

  transcoder_1_status_box:
    dataRef: "transcoder_1_status_box"
    fillColor:
      gradientMode: "none"
      thresholds:
        - { color: "red", level: 0 }
        - { color: "green", level: 1 }
    label:
      units: "status_text"
      mappings:
        - { value: 0, text: "ERROR" }
        - { value: 1, text: "LIVE" }

  # ==============================
  # === SYSTEM RESOURCES =========
  # ==============================
  memory_usage:
    dataRef: "memory_usage"
    fillColor:
      gradientMode: "hue"
      thresholds:
        - { color: "green", level: 0 }
        - { color: "yellow", level: 70 }
        - { color: "red", level: 90 }

  memory_text:
    dataRef: "memory_usage"
    label:
      units: "percent"
      decimalPoints: 0

  disk_usage:
    dataRef: "disk_usage"
    fillColor:
      gradientMode: "hue"
      thresholds:
        - { color: "green", level: 0 }
        - { color: "yellow", level: 70 }
        - { color: "red", level: 90 }

  disk_text:
    dataRef: "disk_usage"
    label:
      units: "percent"
      decimalPoints: 0
