---

#------------------------------------------------------------------------------
# Panel Config

cellIdPreamble: "cell-"
cells:
  encoder1:
    dataRef: "encoder1_health"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds:
        - {color: "green", level: 0}
        - {color: "orange", level: 500}
        - {color: "red", level: 1000}