---

#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

anchorLinks:
  - link: &grafana-home
      url: "https://grafana.com/"
      params: "time"

#------------------------------------------------------------------------------
# Panel Config

cellIdPreamble: "cell-"
cells: 
  drawio:
    link:
      url: "?viewPanel=2&${__url_params}"
      target: "_self"
  docs:
    link:
      url:  "/d/f1eca269-29e0-42d8-94c0-351cbb76f1c0/flow-animation?orgId=1&viewPanel=2"
      target: "_self"
  inbox_depth:
    dataRef: "test-data-large-sin"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds:
        - {color: "green", level: 0}
        - {color: "orange", level: 500}
        - {color: "red", level: 1000}
    link: *grafana-home
  db_transactions:
    dataRef: "test-data-large-cos"
    label:
      separator: "cr"
      units: "ops"
      decimalPoints: 0
    fillColor:
      gradientMode: "hue"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "orange", level: 400}
        - {color: "red", level: 800}
    link: *grafana-home
  start_rate:
    dataRef: "test-data-small-sin"
    label:
      separator: "colon"
      units: "pps"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds:
        - {color: "green", level: 0}
        - {color: "orange", level: 100}
    link: *grafana-home
  active_workers:
    dataRef: "test-data-small-cos"
    label:
      separator: "cr"
      units: "none"
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds:
        - {color: "#888888", level: 0}
        - {color: "light-blue", level: 100}
