---

#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

anchorLinks:
  - link: &grafana-home
      url: "https://grafana.com/"
      params: "time"

#------------------------------------------------------------------------------
# Panel Config

cells: 
  encoder1:
    dataRef: "encoder1_health"
    label:
      separator: "cr"
      units: "ops"
      decimalPoints: 0
    fillColor:
      gradientMode: "hue"
      thresholds:
        - {color: "semi-dark-green", level: 0}
        - {color: "orange", level: 1}